# Form implementation generated from reading ui file 'Project 2\gui2.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VoteWindow(object):
    def setupUi(self, VoteWindow):
        VoteWindow.setObjectName("VoteWindow")
        VoteWindow.resize(500, 600)
        VoteWindow.setMinimumSize(QtCore.QSize(500, 600))
        VoteWindow.setMaximumSize(QtCore.QSize(500, 600))
        self.centralwidget = QtWidgets.QWidget(parent=VoteWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(170, 30, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.title_label.setFont(font)
        self.title_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.id_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.id_input.setGeometry(QtCore.QRect(150, 80, 171, 31))
        self.id_input.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.id_input.setObjectName("id_input")
        self.id_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.id_label.setGeometry(QtCore.QRect(120, 80, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.id_label.setFont(font)
        self.id_label.setObjectName("id_label")
        self.candidates_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.candidates_label.setGeometry(QtCore.QRect(180, 150, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.candidates_label.setFont(font)
        self.candidates_label.setObjectName("candidates_label")
        self.bianca_radio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.bianca_radio.setGeometry(QtCore.QRect(190, 210, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bianca_radio.setFont(font)
        self.bianca_radio.setObjectName("bianca_radio")
        self.edward_radio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.edward_radio.setGeometry(QtCore.QRect(190, 250, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.edward_radio.setFont(font)
        self.edward_radio.setObjectName("edward_radio")
        self.felicia_radio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.felicia_radio.setGeometry(QtCore.QRect(190, 290, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.felicia_radio.setFont(font)
        self.felicia_radio.setObjectName("felicia_radio")
        self.submit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(160, 350, 161, 41))
        self.submit_button.setObjectName("submit_button")
        self.success_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.success_label.setGeometry(QtCore.QRect(100, 420, 301, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.success_label.setFont(font)
        self.success_label.setText("")
        self.success_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.success_label.setObjectName("success_label")
        VoteWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=VoteWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 26))
        self.menubar.setObjectName("menubar")
        VoteWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=VoteWindow)
        self.statusbar.setObjectName("statusbar")
        VoteWindow.setStatusBar(self.statusbar)

        self.retranslateUi(VoteWindow)
        QtCore.QMetaObject.connectSlotsByName(VoteWindow)

    def retranslateUi(self, VoteWindow):
        _translate = QtCore.QCoreApplication.translate
        VoteWindow.setWindowTitle(_translate("VoteWindow", "vote.com"))
        self.title_label.setText(_translate("VoteWindow", "Voting Menu"))
        self.id_label.setText(_translate("VoteWindow", "ID"))
        self.candidates_label.setText(_translate("VoteWindow", "Candidates:"))
        self.bianca_radio.setText(_translate("VoteWindow", "Bianca"))
        self.edward_radio.setText(_translate("VoteWindow", "Edward"))
        self.felicia_radio.setText(_translate("VoteWindow", "Felicia"))
        self.submit_button.setText(_translate("VoteWindow", "Submit Vote"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VoteWindow = QtWidgets.QMainWindow()
    ui = Ui_VoteWindow()
    ui.setupUi(VoteWindow)
    VoteWindow.show()
    sys.exit(app.exec())
